server:
  ip: localhost
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://sxb1plzcpnl473169.prod.sxb1.secureserver.net:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: minyueyou
  jpa:
    show-sql: true #打印执行的sql语句，false则不打印sql
    properties:
      hibernate:
        ddl-auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      open-in-view: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
    tomcat:
      max-swallow-size: 1000MB #最重要的是这行
files:
  upload:
    #文件路径层级尽量少一些 最后一个斜杠必须加上，不然不会创建最后一个文件夹C:\Users\15626\Documents\SummerProject2022\saveAllFile1\

    path: C:\Users\15626\Desktop\files\





