spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sxb1plzcpnl473169.prod.sxb1.secureserver.net:3306/users?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: minyueyou
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 300MB
    tomcat:
      max-swallow-size: 1000MB #最重要的是这行
files:
  upload:
    #linux服务器路径
    path: /home/files/

file-path: http://176.58.99.74:8888/view?relativePath=


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


